---
driver:
  forward_agent: yes
  name: vagrant

provisioner:
  name: chef_zero
  #require_chef_omnibus: 11.16.4
  require_chef_omnibus: 12.2.1
  # Obtained from https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2012r2&v=12.2.1
  chef_metadata_url: 'file:///c:/share/chef/metadata/windows_v12.2.1.txt'

transport:
  name: winrm

platforms:
  - name: win
    driver:
      box: win2012r2
      vm_hostname:
      network:
      - ["private_network", {ip: "192.168.56.31"}]
      # Mount local /Users/apop/chef-kits folder as c:\share on the VM  
      synced_folders:
      - ['/Users/amanly/chef-kits', 'c:/share', 'disabled: false']
      customize:
        cpus: 2
        memory: 2048
suites:
  - name: default
    run_list:
      - recipe[windows::default]
      - recipe[git::default]
      - recipe[iis-webserver::default]
      - recipe[iis-webserver::app_checkout]
    attributes:
      iis-webserver:
        git-repo: https://github.com/alexmanly/myhtml-app
        git-revision: master
        doc-root: c:/inetpub/wwwroot
